### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by boonsboos** [mrsherobrine/ShogiCraft#1]
- [x] test with >1 player at a time
- [x] #2
- [ ] shorthands for commands

### v1.1
- [ ] simultaneous games (multiple games per player)
- [ ] furigoma
- [ ] stats
- [ ] timed matches
- [ ] better command handling

### v1.2
- [ ] rewrite the movement code for certain pieces
- [ ] gui?

**Comment by boonsboos** [comment]
i don't really plan on expanding the plugin as-is, since it currently works just fine.
